In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv(r"C:\Users\User\Desktop\datasets\Churn_Modelling.csv")

In [3]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
#Check the last 5 raws
df.tail()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [5]:
#Find Shape of our dataset 
df.shape

(10000, 14)

In [6]:
#Get Information About Dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [7]:
#Check Null Values in dataset.
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [8]:
#Get Overall Statistics of dataset
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [9]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [10]:
# Dropping Irrelevant Features
df=df.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [11]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [12]:
#Encoding categorical data
df = pd.get_dummies(df,drop_first=True)

In [13]:
df.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,False,False,False
1,608,41,1,83807.86,1,0,1,112542.58,0,False,True,False
2,502,42,8,159660.80,3,1,0,113931.57,1,False,False,False
3,699,39,1,0.00,2,0,0,93826.63,0,False,False,False
4,850,43,2,125510.82,1,1,1,79084.10,0,False,True,False

In [14]:
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [15]:
#store the dataset in X and Y
X = df.drop('Exited', axis=1)
Y = df['Exited']

In [16]:
#handling Imbalanced Data with SMOTE
from imblearn.over_sampling import SMOTE

In [17]:
X_res,Y_res = SMOTE().fit_resample(X,Y)

In [18]:
Y_res.value_counts()

Exited
1    7963
0    7963
Name: count, dtype: int64

In [19]:
#Splitting the dataset into training and testing dataset
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test= train_test_split(X_res,Y_res,test_size=0.2,random_state=42)

In [20]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [21]:
#Logistic Regression
from sklearn.linear_model import LogisticRegression

In [22]:
my_model = LogisticRegression()

In [23]:
my_model.fit(X_train,Y_train)

LogisticRegression()

In [24]:
y_prediction = my_model.predict(X_test)

In [25]:
from sklearn.metrics import accuracy_score

In [26]:
accuracy_score(y_prediction,Y_test)

0.7724419334588826

In [27]:
#SVC- Support Vector Classifire.
from sklearn import svm

In [28]:
#create a model
my_model2=svm.SVC()

In [29]:
#fit data into the model
my_model2.fit(X_train,Y_train)

SVC()

In [30]:
#perform prediction
y_pred2 = my_model2.predict(X_test)

In [31]:
#check model accuracy
accuracy_score(Y_test,y_pred2)

0.8392969240426867

In [32]:
#K-Neighbors Clssifier
from sklearn.neighbors import KNeighborsClassifier

In [33]:
#Crete Model
knn = KNeighborsClassifier()

In [34]:
#Fit data into the model
knn.fit(X_train,Y_train)

KNeighborsClassifier()

In [35]:
#Test the model
y_pred3 = knn.predict(X_test)

In [36]:
#Check ccuarcy score
accuracy_score(Y_test,y_pred3)

0.812617702448211

In [37]:
#Decision Tree Clssifire
from sklearn.tree import DecisionTreeClassifier

In [38]:
#Creat Model
my_dt = DecisionTreeClassifier()

In [39]:
#fit the data into the model
my_dt.fit(X_train,Y_train)

DecisionTreeClassifier()

In [40]:
#test the model - prediction
y_pred4 = my_dt.predict(X_test)

In [41]:
#acuuracy check
accuracy_score(Y_test,y_pred4)

0.7919020715630886

In [42]:
#now make new dataframe for all modeles
final_data = pd.DataFrame({'Models':['LR','SVC','KNN','DT'],
                           'ACCURACY':[accuracy_score(Y_test,y_prediction),
                                       accuracy_score(Y_test,y_pred2),
                                       accuracy_score(Y_test,y_pred3),
                                       accuracy_score(Y_test,y_pred4)]})

In [43]:
final_data

  Models  ACCURACY
0     LR  0.772442
1    SVC  0.839297
2    KNN  0.812618
3     DT  0.791902

In [ ]:
#Here, SVC Model is best model because of higher accuracy.

In [47]:
#Save the Model 
#we are saving SVC Model because it is best model

import joblib
joblib.dump(my_model2,'Bank_Churn_Predi_Model')

['Bank_Churn_Predi_Model']

In [48]:
#check the model 

model=joblib.load('Bank_Churn_Predi_Model')

In [49]:
#give the data to model for checking result
model.predict([[610,42,2,0.0,0,0,0,101348.88,0,0,0]])

array([1], dtype=int64)

# so we can see model give us 1 which meann customer churn the bank

In [59]:
print(X.columns)

Index(['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Geography_Germany',
       'Geography_Spain', 'Gender_Male'],
      dtype='object')

In [61]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
import pickle

pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("model", SVC(probability=True))
])

pipeline.fit(X_train, Y_train)

pickle.dump(pipeline, open("model.pkl","wb"))